name: Super Scrap Squad
favicon: null
layout_spectrum: 0.15976
typography_spectrum: 0.20719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6a319'
    - '#985633'
    - '#ec1b1e'
    - '#2c100f'
    - '#64a0a8'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
